# This docker compose is for testing a real production env locally..
# Simulates a network etc.
version: '3.7'

services:
  # ----- GENERAL SERVICES -------
  service_mq:
    image: rabbitmq:3.13-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - default

  # ----- JOBS MICROSERVICE -------
  service_jobs:
    image: ahmad45123/workup:service_jobs
    depends_on:
      - jobs_db
      - service_mq
    networks:
      - default
      - jobs
    env_file:
      - ./services/jobs/.env

  jobs_db:
    image: cassandra:4.0.7
    networks:
      - jobs # only accessible by the jobs service
    volumes:
      - ./services/jobs/cassandra-config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 20s
      timeout: 10s
      retries: 60
    networks:
      - jobs

  # ----- PAYMENTS MICROSERVICE -------
  service_payments:
    image: ahmad45123/workup:service_payments
    depends_on:
      - payments_db
      - service_mq
    networks:
      - default
      - payments
    env_file:
      - ./services/payments/.env

  payments_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: payments_password
      POSTGRES_USER: payments_user
      POSTGRES_DB: payments_database
    healthcheck:
      test:  ["CMD", "pg_isready"]
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      - payments

  # ----- CONTRACTS MICROSERVICE -------
  service_contracts:
    image: ahmad45123/workup:service_contracts
    depends_on:
      - contracts_db
      - service_mq
    networks:
      - default
      - contracts
    env_file:
      - ./services/contracts/.env

  contracts_db:
    image: cassandra:4.0.7
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 20s
      timeout: 10s
      retries: 60
    networks:
      - contracts

networks:
  default:
  jobs:
  payments:
  contracts:
