version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: payments_password
      POSTGRES_USER: payments_user
      POSTGRES_DB: payments_database
    ports:
      - "5432:5432"