# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker Packeges

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -DskipTests -B package --file pom.xml

    - uses: actions/upload-artifact@v4
      name: Upload JAR artifacts
      with:
        name: jarfiles
        path: '**/target/*.jar'

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Jobs Image
      run: |
        docker build ./services/jobs --tag ahmad45123/workup:service_jobs
        docker push ahmad45123/workup:service_jobs

    - name: Build and push Payments Image
      run: |
        docker build ./services/payments --tag ahmad45123/workup:service_payments
        docker push ahmad45123/workup:service_payments
    
    - name: Build and push Users Image
      run: |
        docker build ./services/users --tag ahmad45123/workup:service_users
        docker push ahmad45123/workup:service_users

    - name: Build and push Contracts Image
      run: |
        docker build ./services/contracts --tag ahmad45123/workup:service_contracts
        docker push ahmad45123/workup:service_contracts
